baseurl = "https://suyu-wiki.github.io/"
languageCode = "en-us"

DefaultContentLanguage = "en"
theme = "shared-bulma-theme"

# Define how many objects appear per pagination.
paginate = 20
# Define build timeout for each page (incl. image processing).
timeout = 300000



[Params]
  Tenant = "suyu"
  BulmaPrimaryShade = "is-dark"
  DiscordURL = "https://discord.gg/u77vRWY"
  TwitterURL = "https://twitter.com/yuzuemu"
  GithubURL = "https://github.com/yuzu-mirror/yuzu"
  GithubGamesWikiURL = "https://github.com/suyu-wiki/suyu-games-wiki"
  GoogleAnalyticsTrackingId = "UA-112443698-1"

[Params.fmt]
  ISO8601 = "2006-01-02T15:04:05-07:00"
  Date = "January 02 2006"

[Languages]
  [Languages.en]
    title = "Suyu"
    tagline = "Nintendo Switch Emulator"
    description = "Suyu is a fork of Yuzu, a highly experimental open-source emulator for the Nintendo Switch."
    weight = 1

[module]
  [[module.mounts]]
  source = "static/images"
  target = "assets/images"
  [[module.mounts]]
  source = 'assets'
  target = 'assets'

[outputs]
home = [ "HTML", "RSS" ]
section = [ "HTML" ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[security]
  [security.funcs]
    getenv = ['^HUGO_', 'TENANT']
